
import com.dropbox.core.DbxException;
import com.dropbox.core.NetworkIOException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.text.Document;

/**
 *
 * @author LENOVO
 */

public class MainFrame extends javax.swing.JFrame {
     
     
    /**
     * Creates new form MainFrame
     */
  public DemoIntegration de=null;
    public MainFrame() throws DbxException {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);// this line of code is used for maximized the jframe
        initComponents(); 
         try {
            de = new DemoIntegration();
        } catch (NetworkIOException ex) {
           JOptionPane.showMessageDialog(null, "No internet please connect it to the Internet  ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpanel = new javax.swing.JPanel();
        footerpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        footerpanel1 = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jScrollPanelower = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPaneupper = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        jLabel2 = new javax.swing.JLabel();
        driveselect = new javax.swing.JComboBox<>();
        ParentTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textpane = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        text = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        FileMenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        NewFile = new javax.swing.JMenu();
        NormalText = new javax.swing.JMenuItem();
        Java = new javax.swing.JMenuItem();
        Open = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        save = new javax.swing.JMenuItem();
        saveall = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Closeall = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        Undo = new javax.swing.JMenuItem();
        Redo = new javax.swing.JMenuItem();
        cut = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Paste = new javax.swing.JMenuItem();
        Helpmenu = new javax.swing.JMenu();
        CheckUpdates = new javax.swing.JMenuItem();
        AboutCor2Crust = new javax.swing.JMenuItem();
        AboutDevelopers = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        footerpanel.setBackground(new java.awt.Color(255, 255, 255));
        footerpanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Help");

        javax.swing.GroupLayout footerpanelLayout = new javax.swing.GroupLayout(footerpanel);
        footerpanel.setLayout(footerpanelLayout);
        footerpanelLayout.setHorizontalGroup(
            footerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerpanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1300, Short.MAX_VALUE))
        );
        footerpanelLayout.setVerticalGroup(
            footerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        backgroundpanel.add(footerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1370, 20));

        footerpanel1.setBackground(new java.awt.Color(204, 204, 204));
        footerpanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout footerpanel1Layout = new javax.swing.GroupLayout(footerpanel1);
        footerpanel1.setLayout(footerpanel1Layout);
        footerpanel1Layout.setHorizontalGroup(
            footerpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        footerpanel1Layout.setVerticalGroup(
            footerpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        backgroundpanel.add(footerpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, -1, 30));

        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPanelower.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPanelower.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Open Selected File");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 40));

        jScrollPanelower.setViewportView(jPanel2);

        sidepanel.add(jScrollPanelower, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 230, 280));

        tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeMouseClicked(evt);
            }
        });
        tree.setModel(new FileSystemModel(new File("f://")));
        jScrollPaneupper.setViewportView(tree);

        sidepanel.add(jScrollPaneupper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 290));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Directory ");
        sidepanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 30));

        driveselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Drive", "C:\\"+"\\" , "D:\\"+"\\", "E:\\"+"\\" ,"F:\\"+"\\" }));
            driveselect.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    driveselectActionPerformed(evt);
                }
            });
            sidepanel.add(driveselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 230, 30));

            backgroundpanel.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 230, 630));

            ParentTab.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
            ParentTab.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

            textpane.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
            textpane.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
            textpane.setDragEnabled(true);
            jScrollPane1.setViewportView(textpane);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
            );

            ParentTab.addTab("Editor", jPanel1);

            backgroundpanel.add(ParentTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 1140, 560));

            jButton3.setText("PULL");
            jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });
            backgroundpanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 60, 30));

            jButton4.setText("PUSH");
            jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });
            backgroundpanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 60, 30));

            jButton5.setText("VIEW");
            jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });
            backgroundpanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 40, 60, 30));

            jButton2.setText("DELETE");
            jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
            backgroundpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, 60, 30));

            text.setText("Enter the name of file to pull");
            text.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    textActionPerformed(evt);
                }
            });
            backgroundpanel.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 170, 30));

            jButton6.setText("Make Folder");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });
            backgroundpanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, -1, -1));

            jButton7.setText("Close Tab");
            jButton7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton7ActionPerformed(evt);
                }
            });
            backgroundpanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 40, -1, -1));

            getContentPane().add(backgroundpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 700));

            FileMenuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            FileMenuBar.setForeground(new java.awt.Color(255, 255, 255));
            FileMenuBar.setAutoscrolls(true);
            FileMenuBar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

            File.setText("File");
            File.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    FileActionPerformed(evt);
                }
            });

            NewFile.setText("New File");

            NormalText.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
            NormalText.setText("Normal Text");
            NormalText.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    NormalTextActionPerformed(evt);
                }
            });
            NewFile.add(NormalText);

            Java.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
            Java.setText("Java");
            Java.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    JavaActionPerformed(evt);
                }
            });
            NewFile.add(Java);

            File.add(NewFile);

            Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
            Open.setText("Open");
            File.add(Open);
            File.add(jSeparator1);

            save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
            save.setText("Save");
            save.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    saveActionPerformed(evt);
                }
            });
            File.add(save);

            saveall.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
            saveall.setText("Save All");
            File.add(saveall);
            File.add(jSeparator2);

            Closeall.setText("Close All");
            File.add(Closeall);

            Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
            Exit.setText("Exit");
            Exit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ExitActionPerformed(evt);
                }
            });
            File.add(Exit);

            FileMenuBar.add(File);

            Edit.setText("Edit");

            Undo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
            Undo.setText("Undo");
            Undo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    UndoActionPerformed(evt);
                }
            });
            Edit.add(Undo);

            Redo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
            Redo.setText("Redo");
            Edit.add(Redo);

            cut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
            cut.setText("Cut");
            Edit.add(cut);
            Edit.add(jSeparator3);

            Paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
            Paste.setText("Paste");
            Edit.add(Paste);

            FileMenuBar.add(Edit);

            Helpmenu.setText("Help");

            CheckUpdates.setText("Check  Updates");
            Helpmenu.add(CheckUpdates);

            AboutCor2Crust.setText("About Cor2Crust");
            AboutCor2Crust.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AboutCor2CrustActionPerformed(evt);
                }
            });
            Helpmenu.add(AboutCor2Crust);

            AboutDevelopers.setText("About Developers");
            AboutDevelopers.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    AboutDevelopersMouseClicked(evt);
                }
            });
            AboutDevelopers.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AboutDevelopersActionPerformed(evt);
                }
            });
            Helpmenu.add(AboutDevelopers);

            FileMenuBar.add(Helpmenu);

            setJMenuBar(FileMenuBar);

            setBounds(0, 0, 1383, 742);
        }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void NormalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalTextActionPerformed

       String name = JOptionPane.showInputDialog("Enter Name");
      String nametext = JOptionPane.showInputDialog("Enter  Name");
      /* JTextPane panel = new JTextPane();
       JScrollPane jk = new JScrollPane(panel);
       jk.setName(name);     
       ParentTab.add(jk);*/ 
       ReturnComponent rc = new ReturnComponent();
       rc.setName(name);
      
      // gt.settextPaneName(nametext);
       ParentTab.add(rc.getComponent());

    }//GEN-LAST:event_NormalTextActionPerformed

    private void AboutDevelopersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutDevelopersActionPerformed
      
        new About_Developers().setVisible(true);
       
       
    }//GEN-LAST:event_AboutDevelopersActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      // textpanes.setContentType("text/html");
     


       
    }//GEN-LAST:event_formWindowOpened

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
                                                 
        JFileChooser fc = new JFileChooser(new File("F:"));
       fc.showSaveDialog(this);
       File f = fc.getSelectedFile();
        try {
           try (FileWriter fw = new FileWriter(f)) 
           {
               String text = textpane.getText();
               fw.write(text); 
           }
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }//GEN-LAST:event_saveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       StringBuilder sb= new StringBuilder();
        File file = new File(treevar);
        try {
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String s;
                while ((s= br.readLine())!=null) {
                    sb.append(s);
                   // textpane.setText(s);
                }
                 textpane.setText(sb.toString());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void treeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMouseClicked
     treevar = tree.getSelectionPath().toString().replaceAll("[\\[\\]]", "").replace(", ", "\\");
    }//GEN-LAST:event_treeMouseClicked

    private void driveselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driveselectActionPerformed
      getCombobox = driveselect.getSelectedItem().toString();
      text.setText(getCombobox);
      File filecombo = new File(getCombobox);
    }//GEN-LAST:event_driveselectActionPerformed

    private void UndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UndoActionPerformed

    private void AboutDevelopersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutDevelopersMouseClicked
        
        
    }//GEN-LAST:event_AboutDevelopersMouseClicked

    private void AboutCor2CrustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutCor2CrustActionPerformed
            new AboutCompany().setVisible(true);
    }//GEN-LAST:event_AboutCor2CrustActionPerformed

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed
        textpane.setText(null);
    }//GEN-LAST:event_FileActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    
       String[] choices;
        try {
            ArrayList al = de.listfiles(); 
            if(al.size()==0){JOptionPane.showMessageDialog(null, "No files on the List Please push One to get The Solution");}
            else if(al.size()==1){
                 List<String> tw= new ArrayList<String>(al.size());
             String slocale=al.get(0).toString();
            tw.add(slocale.substring(slocale.lastIndexOf('/')+1));
             choices=new String[tw.size()];
              choices[0]=tw.get(0);
            System.out.println(choices[0]);
               String input = (String) JOptionPane.showInputDialog(null, "Choose now...", "HERE ARE THE LIST OF FILES IN  THE BOX", JOptionPane.QUESTION_MESSAGE, null,choices,choices[0]); // Initial choice
    System.out.println(input);
          //  JOptionPane.showMessageDialog(null,"Succesfully fetched 1 doc");
            }
            else{
            List<String> tw= new ArrayList<String>(al.size());
            for(int i=0;i<al.size();i++){ 
                String slocale=al.get(i).toString();
            tw.add(slocale.substring(slocale.lastIndexOf('/')+1)); 
            }
            choices=new String[tw.size()];
                   
            for(int j=0;j<tw.size();j++)
            {
            choices[j]=tw.get(j);
             System.out.println(choices[j]);
            }
         
    String input = (String) JOptionPane.showInputDialog(null, "Choose now...", "HERE ARE THE LIST OF FILES IN  THE BOX", JOptionPane.QUESTION_MESSAGE, null,choices,choices[1]); // Initial choice
    System.out.println(input);
            }   
            
        } catch (DbxException ex  ) {
          JOptionPane.showMessageDialog(null, ex);
        }   catch(ArrayIndexOutOfBoundsException e){JOptionPane.showMessageDialog(null,"Empty  Folder");}
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 JFileChooser fc = new JFileChooser(new File("F:"));
       fc.showSaveDialog(this);
        File f= fc.getSelectedFile();   
        de.fuckinUpload(f);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String[] choices;    
       
        try {
            ArrayList al = de.listfiles();
            List<String> tw= new ArrayList<String>();
          for(int i=0;i<al.size();i++){
                String slocale=al.get(i).toString();
            tw.add(slocale.substring(slocale.lastIndexOf('/')+1)); 
            }
            choices=new String[tw.size()];
                    
            for(int j=0;j<tw.size();j++)
            {
            choices[j]=(String)tw.get(j);
            }
         
    String input =(String) JOptionPane.showInputDialog(null, "Choose now...",
        "HERE ARE THE LIST OF FILES IN  THE BOX", JOptionPane.QUESTION_MESSAGE, null,choices,choices[1]); // Initial choice

    System.out.println(input);
    text.setText(input);
   de.openFile(input);
      String name = JOptionPane.showInputDialog("Enter Name");
      
       JTextPane panel = new JTextPane();
       JScrollPane jsp = new JScrollPane(panel);
       jsp.setName(name);
       ParentTab.add(jsp);
     
    
    
        } catch (DbxException ex) {
          JOptionPane.showMessageDialog(null, ex);
        } catch (IOException ex) {       
         JOptionPane.showMessageDialog(null,"Sorry cannot Download File");
      }       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textActionPerformed

    private void JavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JavaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
               de.makeDir();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String[] choices;
        try {
            ArrayList al = de.listfiles();
             List<String> tw= new ArrayList<String>(al.size());
            System.out.println(al.get(0));
            if(al==null){JOptionPane.showMessageDialog(null, "No folders to List");}
            else if(al.size()==1){
             String slocale=al.get(0).toString();
            tw.add(slocale.substring(slocale.lastIndexOf('/')+1));
             choices=new String[tw.size()];
              choices[0]=tw.get(0);
            System.out.println(choices[0]);
               String input = (String) JOptionPane.showInputDialog(null, "Choose now...", "HERE ARE THE LIST OF FILES IN  THE BOX", JOptionPane.QUESTION_MESSAGE, null,choices,choices[0]); // Initial choice
    System.out.println(input);de.delete(input);
           JOptionPane.showMessageDialog(null,"Succesfully Deleted");
            }
            else{
           
            for(int i=0;i<al.size();i++){
                String slocale=al.get(i).toString();
            tw.add(slocale.substring(slocale.lastIndexOf('/')+1)); 
            }
            choices=new String[tw.size()];
                   
            for(int j=0;j<tw.size();j++)
            {
            choices[j]=tw.get(j);
             System.out.println(choices[j]);
            }
         
    String input = (String) JOptionPane.showInputDialog(null, "Choose now...", "HERE ARE THE LIST OF FILES IN  THE BOX", JOptionPane.QUESTION_MESSAGE, null,choices,choices[1]); // Initial choice
    System.out.println(input);
    de.delete(input);
     JOptionPane.showMessageDialog(null,"Succesfully Deleted");
            }   
            
        } catch (DbxException ex  ) {
          JOptionPane.showMessageDialog(null, ex);
        }   catch(ArrayIndexOutOfBoundsException e){JOptionPane.showMessageDialog(null,"Empty  Folder");}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MainFrame().setVisible(true);
            } catch (DbxException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutCor2Crust;
    private javax.swing.JMenuItem AboutDevelopers;
    private javax.swing.JMenuItem CheckUpdates;
    private javax.swing.JMenuItem Closeall;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenuBar FileMenuBar;
    private javax.swing.JMenu Helpmenu;
    private javax.swing.JMenuItem Java;
    private javax.swing.JMenu NewFile;
    private javax.swing.JMenuItem NormalText;
    private javax.swing.JMenuItem Open;
    private javax.swing.JTabbedPane ParentTab;
    private javax.swing.JMenuItem Paste;
    private javax.swing.JMenuItem Redo;
    private javax.swing.JMenuItem Undo;
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JMenuItem cut;
    private javax.swing.JComboBox<String> driveselect;
    private javax.swing.JPanel footerpanel;
    private javax.swing.JPanel footerpanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPanelower;
    private javax.swing.JScrollPane jScrollPaneupper;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem save;
    private javax.swing.JMenuItem saveall;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JTextField text;
    public javax.swing.JTextPane textpane;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables
    String treevar;
    String time;
    String getCombobox;
}
